<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>A Less crappy, simple YAML...but still a little crappy :).
A work in progress
</string>
	<key>fileTypes</key>
	<array>
		<string>yaml</string>
		<string>yml</string>
	</array>
	<key>name</key>
	<string>YAML (simple)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#evil-tabs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#document-markers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#multi-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>address-tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.address.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([&amp;\*][a-zA-Z0-9\-_]+)[ \r\n]*(#.*)?(?=$)</string>
		</dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.left.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.yaml-simple</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])[ \r\n]*(?:(#.*)?|(?=$|,|\}|\]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.right.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(!!regex)[ ]*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>[ \r\n]*(?:(,)\n?|(?=\]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.paren.separator.yaml-simple</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline-sublime-regex</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=(?:\[|,|[ \r\n]))</string>
							<key>end</key>
							<string>(?=(?:,\n?|\]))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#inline-values</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(!![\w//]+)[ ]*</string>
					<key>end</key>
					<string>[ \r\n]*(?:(,)\n?|(?=\]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.paren.separator.yaml-simple</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=(?:\[|,|[ \r\n]))</string>
							<key>end</key>
							<string>(?=(?:,\n?|\]))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#inline-values</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-array-values</string>
				</dict>
			</array>
		</dict>
		<key>associative-array</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.left.yaml-simple</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})[ \r\n]*(?:(#.*)?|(?=$|,|\}|\]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.right.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-keys</string>
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>(?:true|false|TRUE|FALSE|True|False|yes|no)[ ]*(#.*)?(?=$)</string>
			<key>name</key>
			<string>constant.language.boolean.yaml-simple</string>
		</dict>
		<key>cast-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.multi-line.yaml-simple</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:(!![\w//]+)[ ]+)?([|&gt;][-+\d\r\n]*)[ \r\n]*(#.*)?$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(!!regex)[ ]+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sublime-regex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(!![\w//]+)[ ]+</string>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#values</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>document-markers</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.document.start.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.document.end.yaml-simple</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:(-{3})|(\.{3}))[ \r\n]*(?:(#.*)?$)</string>
		</dict>
		<key>evil-tabs</key>
		<dict>
			<key>match</key>
			<string>\t+</string>
			<key>name</key>
			<string>invalid.illegal.tab.yaml-simple</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>begin</key>
			<string>^[ \r\n]*(?:(-)[ \r\n]*)?(?=[\{\[])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.list.yaml-simple</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(#.*)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#associative-array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
			</array>
		</dict>
		<key>inline-address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.class.address.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([&amp;\*][a-zA-Z0-9\-_]+)[ ]*(?=(?:,|\}|\]))</string>
				</dict>
			</array>
		</dict>
		<key>inline-array-values</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=(?:\[|,|[ \r\n]))</string>
			<key>end</key>
			<string>[ \r\n]*(?:(,)\n?|(?=\]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.separator.yaml-simple</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-values</string>
				</dict>
			</array>
		</dict>
		<key>inline-boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:true|false|TRUE|FALSE|True|False|yes|no)[ ]*(?=(?:,|\}|\]))</string>
					<key>name</key>
					<string>constant.language.boolean.yaml-simple</string>
				</dict>
			</array>
		</dict>
		<key>inline-cast-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(!!regex)[ ]+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=(?:,\n?|\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline-sublime-regex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(!![\w//]+)[ ]+</string>
					<key>end</key>
					<string>(?=(?:,\n?|\}))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline-values</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>inline-keys</key>
		<dict>
			<key>begin</key>
			<string>(?x)[\ \r\n]*(?:
    (?:
        (\w(?:.*?[^\ ])?|&lt;&lt;)(?:[\ \r\n]*(\:)(?:[\ \r\n]+)) |
        ([']((?:(?:\\.)|(?:[^'\\]|'{2}))*?)['])(\:)(?:[\ \r\n]+)|
        (["]((?:(?:\\.)|(?:[^"\\]|\\"))*?)["])(\:)(?:[\ \r\n]+)
    )
)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.yaml-simple</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-separator.yaml-simple</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.yaml-simple</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.yaml-simple</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-separator.yaml-simple</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.tag.yaml-simple</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.yaml-simple</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.key-separator.yaml-simple</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[ \r\n]*(?:(,)\n?|(?=\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.paren.separator.yaml-simple</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-cast-values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-values</string>
				</dict>
			</array>
		</dict>
		<key>inline-numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[+\-]?[\d_]+(?:(?:\.[\d_]*)?(?:[eE][+\-]?[\d_]+)?)?[ ]*(?=(?:,|\}|\]))</string>
					<key>name</key>
					<string>constant.numeric.yaml-simple</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[+\-]?\.inf\b|NaN\b|0x[\dA-Fa-f_]+|0b[10_]+[ ]*(?=(?:,|\}|\]))</string>
					<key>name</key>
					<string>constant.numeric.yaml-simple</string>
				</dict>
			</array>
		</dict>
		<key>inline-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>!!regex (["](?:(?:\\.)|(?:[^"\\]|\\"))*?["])[ ]*(?=(?:,|\}|\]))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>["]</string>
					<key>end</key>
					<string>["][ \r\n]*(?=(?:,|\}|\]))</string>
					<key>name</key>
					<string>string.yaml-simple</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:(?:\\.)|(?:[^"\\]|\\"))*?</string>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(['](?:(?:\\.)|(?:[^'\\]|'{2}))*?['])[ ]*(?=(?:,|\}|\]))</string>
				</dict>
			</array>
		</dict>
		<key>inline-sublime-regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')[ ]*(?=(?:,|\}|\]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")[ ]*(?=(?:,|\}|\]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>inline-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-address</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-numerics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#associative-array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\{\[\}\],]*</string>
					<key>name</key>
					<string>unmatched.yaml-simple</string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.yaml-simple</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \r\n]*(#.*)$</string>
		</dict>
		<key>multi-line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)^([\ ]*)(?:([\-])([\ ]+))?
    (?:
        (\w(?:.*?[^\ ])?|&lt;&lt;)(?:[\ \r\n]*(\:)(?:[\ \r\n]+)) |
        ([']((?:(?:\\.)|(?:[^'\\]|'{2}))*?)['])(\:)(?:[\ \r\n]+) |
        (["]((?:(?:\\.)|(?:[^"\\]|\\"))*?)["])(\:)(?:[\ \r\n]+)
    )
    (!!regex)[\ ]+([|&gt;][-+\d\r\n]*)[\ ]*(\#.*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.multi-line.yaml-simple</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.list.yaml-simple</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *$|\1\3 {2})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)^([\ ]*)(?:([\-])([\ ]+))?
    (?:
        (\w(?:.*?[^\ ])?|&lt;&lt;)(?:[\ \r\n]*(\:)(?:[\ \r\n]+)) |
        ([']((?:(?:\\.)|(?:[^'\\]|'{2}))*?)['])(\:)(?:[\ \r\n]+) |
        (["]((?:(?:\\.)|(?:[^"\\]|\\"))*?)["])(\:)(?:[\ \r\n]+)
    )
    (?:(!![\w//]+)[\ ]+)?([|&gt;][-+\d\r\n]*)[\ ]*(\#.*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>support.type.yaml-simple</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.multi-line.yaml-simple</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.list.yaml-simple</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *$|\1\3 {2})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.*</string>
							<key>name</key>
							<string>multiline.text.yaml-simple unmatched.yaml-simple</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[+\-]?[\d_]+(?:(?:\.[\d_]*)?(?:[eE][+\-]?[\d_]+)?)?[ ]*(#.*)?(?=$)</string>
					<key>name</key>
					<string>constant.numeric.yaml-simple</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[+\-]?\.inf\b|NaN\b|0x[\dA-Fa-f_]+|0b[10_]+[ ]*(#.*)?(?=$)</string>
					<key>name</key>
					<string>constant.numeric.yaml-simple</string>
				</dict>
			</array>
		</dict>
		<key>single-line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)^[\ ]*(?:
    (?:([\-?])(?:[\ \r\n]+))?
    (?:
        (\w(?:.*?[^\ ])?|&lt;&lt;)(?:[\ \r\n]*(\:)(?:[\ \r\n]+|(?=$))) |
        ([']((?:(?:\\.)|(?:[^'\\]|'{2}))*?)['])(\:)(?:[\ \r\n]+|(?=$))|
        (["]((?:(?:\\.)|(?:[^"\\]|\\"))*?)["])(\:)(?:[\ \r\n]+|(?=$))
    )
)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.list.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>meta.tag.yaml-simple</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.key-separator.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(#.*)$</string>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cast-values</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.list.yaml-simple</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^( *)(-|\?)[ ]*(#.*)?$</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(["](?:(?:\\.)|(?:[^"\\]|\\"))*?["])[ ]*(#.*)?(?=$)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>["]</string>
					<key>end</key>
					<string>["][ \r\n]*(#.*)?(?=$)</string>
					<key>name</key>
					<string>string.yaml-simple</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:(?:\\.)|(?:[^"\\]|\\"))*?</string>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml-simple</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(['](?:(?:\\.)|(?:[^'\\]|'{2}))*?['])[ ]*(#.*)?(?=$)</string>
				</dict>
			</array>
		</dict>
		<key>sublime-regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')[ ]*(#.*)?(?=$)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")[ ]*(#.*)?(?=$)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.yaml-simple</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.yaml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#address-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#associative-array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numerics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>unmatched.yaml-simple</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yaml-simple</string>
	<key>uuid</key>
	<string>a3a8b36d-b4c3-4212-bb86-d1d18301bf5a</string>
</dict>
</plist>
